coinchange: coinchange.cpp
	g++ coinchange.cpp -o coinchange


exhaust: coinchange_exhaustive.cpp
	g++ coinchange_exhaustive.cpp -o coinchange_exhaustive

clean:
	rm -f coinchange, coinchange_exhaustive